### ISSUE TITLE
Create Logic for requesting to join a project

### ISSUE THREAD

**Issue by CreativeCreature7** [CreativeCreature7/yazameet#21]

**Comment by CreativeCreature7** [comment]
- include mailing for both the one who requested and the group manager
- include mail for the one who requested when the request is approved or disapproved
- ability to cancel requests
- see pending requests (requests I sent, join requests for my project)

**Comment by froozy3** [comment]
how can i join?

**Comment by CreativeCreature7** [comment]
@froozy3 

> how can i join?

Hey :) Thanks for your interest in the project are you from my university?
you can set up a meeting with me here: https://cal.com/guybenhemo/30min
